# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

trigger:
- master
- releases/*

pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  buildConfiguration: 'Release'
  Prerelease: ci
  Major: '0'
  Minor: '1'
  Patch: '0'

steps:
- script: |
    dotnet build --configuration $(buildConfiguration)
  displayName: Build
  env:
    pswd: $(dockerPassword)
- script: find -wholename '**/Dockhand.Test*/*.csproj' ! -name '*.Test.Common.csproj' -print | xargs -i dotnet test {} --configuration $(buildConfiguration) --logger trx
  displayName: Run Tests
  failOnStderr: true

- script: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: Dotnet Publish

- task: DotNetCoreCLI@2
  displayName: dotnet pack
  inputs:
    command: pack
    packDirectory: '$(Build.ArtifactStagingDirectory)/packages'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
