# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

trigger:
- master
- releases/*

pool:
  vmImage: 'Ubuntu 16.04'
  
variables:
  buildConfiguration: 'Release'
  Prerelease: pre
  Major: '0'
  Minor: '1'
  Patch: '0'

steps:
- script: |
    dotnet build --configuration $(buildConfiguration) --version-suffix $(Build.BuildId)
  displayName: Build
  env:
    pswd: $(dockerPassword)
- script: find -wholename '**/Dockhand.Test*/*.csproj' ! -name '*.Test.Common.csproj' -print | xargs -i dotnet test {} --configuration $(buildConfiguration) --logger trx
  displayName: Run Tests
  failOnStderr: true

- script: dotnet publish ./src/Dockhand/Dockhand.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --version-suffix $(Prerelease)-$(Build.BuildNumber)
  condition: ne(variables['Prerelease'], '')
  displayName: Dotnet Publish (Prerelease)

- script: dotnet publish ./src/Dockhand/Dockhand.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  condition: eq(variables['Prerelease'], '')
  displayName: Dotnet Publish (Release)

- script: dotnet pack ./src/Dockhand/Dockhand.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/package -p:PackageVersion=$(Major).$(Minor).$(Patch)-$(Prerelease)-$(Build.BuildNumber)
  condition: ne(variables['Prerelease'], '')
  displayName: Dotnet Pack (Prerelease)

- script: dotnet pack ./src/Dockhand/Dockhand.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/package -p:PackageVersion=$(Major).$(Minor).$(Patch).$(Build.BuildId)
  condition: eq(variables['Prerelease'], '')
  displayName: Dotnet Pack (Release)

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
